language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "maries-roc-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: maries-roc-julia # see README
  api_key:
    secure: Tt3/juGjpgJ9psK5HWN6KZaI64U1qmk8Fv/Gq7Nh78/+RqRF1keLq4ztvOT6KhTLpyVAQLmOXqEI4AGd3F6e8xmufLyOHn/+xJ4c5IIj6/6V9cK6ILFKmThSMeBZSwT2qN6TjH1Fe5Agd8SaO/3He33kNGmmidgkmoy8wuvO8rSFq6t8cQQ5YH+OkWTLY3WGm7vfwKyn/XEMgj3V6XiesjTEd5Zuz6n/OiPx7nFo7Jcj/sq5dkjxBdf+Ug1yvyWtqmxd5FxqRbK5BF+xHCIfdAW0yYz+Luyzpdllh0uzzU/G1rILyoO0rGp5MemSV6fkP4bmawBiQDv2WI7QQciimKc30BmSbzi1YNOQInekC14ysBYMKkNRNns6WKo7zWCYueprc8qUVL0JR61/mxllmAPRK8BrZHXq1GdVqLGExHm8nrzNF4M8haD4n39RFGxLrMFpDj5PtpGsody1SEQLdjRzaQKEmEKZjhFhRPrffvjDxpA/ZAebSWMNrJ89YIP9clFIawDFHRGwDl2ijd/mMl8lBre9/c6tx0UhVoUIR7Sc0d2c3O+egtDMUDXnu0N0hEDpy1U+h/IEFuiWKCqpdZcGZPE/DliuBGMnV0sMO+7xznXJEswgT6/fFy5I/fw+BfpfgdMNJOOZxDzYcD4CDdg8FrYhHPCyhb6J7Y44e9A= # see README
