language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "maries-roc-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: maries-roc # see README
  api_key:
    secure: fW2RUW1Qs4TehUSKThKkGeKTwVGpkbxDzujvY5RxpD9iwF0shFHUuWrr4s/iPQTB6oGuKIHsbXSH2dax0T8hnpnuf5fr2DmfD6WjeH2KqMM0VCgmGBQY2SXYp2Bp6puVo+O9ePsLcgVzDNAka+As9lPlf5sLllrPIVgg6ft+naZKs8C5XYpbRe83wdIC94B++sVQ450wNURkWtYXzgeUVA3JSa4t2C4xboYE96re2erD58LI4IHElcGP+XQUA7c+Aq/0QTYOZiNcYMi6+cbTNN94QT21YFNYI8gGOxSds0Afs2yWFmcy6/0Z9qgoRXEg2IwtM2CS7y4MuDrE+mnp2iuS8YOLht9nan/YiuqizY288zG6QASuK5N0GrLITn4UGjYh7n65NAsuscgRgItZvgwdKlNnbtWcRrvULo5RqIcH5z3E60ToK6K129NEKfdV1vjJ99LD3RiPlUA04TBKB1AaBmgYpRN/wIu3LCzANKPFyyKDm9SibRaRTLI+3E1o0/iRheWKdcPTtwKROeeI2xcNU6YynqWES/Bh/KzbYE5yTUuyBOvAjZbFrAV7wajpUja0L683pp/thyofy2xTGBn6GZR2dCZlJ6TW4hJD5ZNA4p0Sl/4JrGt9pWjo/Jc91CoFMgc8LETXI+PzL0Up7ZC4nTgi8SGIKpD3tEmRgw8= # see README
