language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "maries-roc-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: maries-roc # see README
  api_key:
    secure: eJDAxy2P9APVq/x+YwB2g1G1Ab2NDKlg35GiQHcg8ChOEk2I63IgVQA65a/6u7iWeglVxNX8j/tTvaKY7SBeR+RkD4hBSVcHW/dhHX59s+TxuvO2F7ps7vlvn+bXxwJ4dQH2FM10hbrmdjXGLzmaNKo7ljdOr3ai2kgioEspzAXPH/18Qe/KQl0scFAMJXn2sCQrWkWp9T/RZTT1GJdYks30J1oggfwCG3zRhm9OfgiXPQjuIZGVLrg6NKK5VKCSKjcFVxEmrdOuxsY+s9I1Ee1MXiYcjxMJc9zXDQMaRDMoGGko7B6B/k8hYgRnGEqLQerTHK7VGvSI66zkbWMg3veL3MaYIx7zYbhmTfEKOfzLW3ZqxAxUa//WBrhqw90oOR2i29OoP+86DNZQetIn/YGy+sqjhNCCk4kiywTFW/CjRIAW7kMCPejh+7r4D+sY1CB1NEm+VKJgrrLQ1q4wAH/+kzE6vHTeoHkqD/cD9sSuGBzoDspfwXhr1CbeYFOQueSShDGTM8w2jLnerEkAPDH/x5u4eYgtIgzbV3VbkqxY957+qQp/DrjZPE72K30q7cDwE4qHWzShO5UoIhp7D5iyC09bLt8MlaQ/PTEH93f/39VZtayQJyLvTs5eKhiKOB7pfrvk8F0r8XlMFNpHiJMa8GvOdVdSOzAo7INBOfc= # see README
