language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "maries-roc-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: maries-roc # see README
  api_key:
    secure: Jn009d6rLGD7u/Scv+nM+Mszx2gvW+p83LB4fOEhragQ/10wItoZqo/F1tYyIyiqsUuB2lITzHSTXBgH6NJ4HGlsF2wJoTJU3Qd5k3rCdMsZsTvsFQZZFtpCFo4KOmb/xggu9nCnQUqqeFmxUZeO/clPiO54H+T64livkUqORM+e2gWwrLqHU/98LbE8QIDFc+ZHPaW738YY51md1rOkOB3bGxBp8F7wmlMEeGkP2o4EC5dhi7nfACQRrFBRygX1Cl6Lbd/epFdXr10R1dBVvkV0y3ohXGay9g75TpXpKWVNzlmZ776Np2dKhFm4f2y8FuX/lGpRmTD8L8Jex8oy5RjiLnKM33JY/77TnGBI1QhIqF4E6S0+fEdC4hi4SLFbOX60mu0XAxx9vtXbZ8b+X9V/eU/fSIbgQ4FuOxqNAU09VF8ZPKYPVK4JBL1BfHcjDdkk/BbPkmf8A2cErHrWDX/9Ck0Y+lWLcKiOROW2jQGar+0bZKc6aTOGSYXFkP17n6n2jNW1jodBDLKBJo+OGUYRN18hqlssxphRczod+UpFu6MtQZ6snscPYm8hnHEkQiVMbHqNsdbFcJpHPW8wUVletvRiSX4krxFWslI9y8cm957An+9hBvZnEi6swX0T1iP8om1ei3ZYpx3fxtaqMtSj4UpQ21r2ck0M7DYlhb8= # see README
